services:
  - type: web
    name: pdf-rag-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: data
      mountPath: /app/uploads
      sizeGB: 1 